# Generated by Django 3.1.6 on 2021-03-31 12:03

from __future__ import unicode_literals
from django.db import migrations, models
from datetime import date
from django.core.files import File
import os
from django.conf import settings

CATEG_LIST = [
    {'name': 'Shopping',
     'icon': 'online-shopping.svg',
     'slug': 'shopping'
     },
    {'name': 'Food & Drink',
     'icon': 'fast-food.svg',
     'slug': 'food-drink'
     },
    {'name': 'Circus',
     'icon': 'circus.svg',
     'slug': 'circus'
     },
    {'name': 'Beauty',
     'icon': 'beauty.svg',
     'slug': 'beauty'
     },
    {'name': 'Fitness',
     'icon': 'fitness.svg',
     'slug': 'fitness'
     },
    {'name': 'Games',
     'icon': 'games.svg',
     'slug': 'games'
     },
    {'name': 'Sports',
     'icon': 'sport.svg',
     'slug': 'sports'
     },
    {'name': 'Healthcare',
     'icon': 'healthcare.svg',
     'slug': 'healthcare'
     },
    {'name': 'Places',
     'icon': 'places.svg',
     'slug': 'places'
     },
    {'name': 'Hotels',
     'icon': 'hotels.svg',
     'slug': 'hotels'
     },
    {'name': 'Theater',
     'icon': 'theater.svg',
     'slug': 'theater'
     },
    {'name': 'Bar & Club',
     'icon': 'bar-club.svg',
     'slug': 'bar-club'
     },
]


def add_data(apps, shema_editor):
    categ_listing = apps.get_model('listing', 'ListingCategory')
    for item in CATEG_LIST:
        obj,created = categ_listing.objects.get_or_create(name=item['name'], slug=item['slug'])
        icon_path = os.path.join(settings.BASE_DIR, 'static', 'images', item['icon'])
        with open(icon_path, 'rb') as icon_thumb:
            icon_instance = File(icon_thumb, os.path.basename(icon_path))
            obj.icon = icon_instance
            obj.save()


def remove_data(apps, schema_editor):
    categ_listing = apps.get_model('listing', 'ListingCategory')
    for item in CATEG_LIST:
        obj = categ_listing.objects.get(name=item['name'])
        obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [migrations.RunPython(add_data,remove_data)
    ]
