# Generated by Django 3.1.6 on 2021-04-02 08:29


from __future__ import unicode_literals
from django.db import migrations, models
from datetime import date
from django.core.files import File
import os
from django.conf import settings


LISTINGS = [
    {'category' : 'food-drink',
     'username' : 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name' :'Japanesse Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone':'+4932 9329 239 ',
     'email': 'japanesse@restaurant.com',
     'icon': 'list-1.webp',
    },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Chinesse Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'chinesse@restaurant.com',
     'icon': '1.webp',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Romanian  Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'romanian@restaurant.com',
     'icon': 'zensushi_take_away-1.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Moldavian Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'moldavian@restaurant.com',
     'icon': '21.jpg',
     },
    
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'KFC Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'kfc@restaurant.com',
     'icon': 'KFC.png',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Adelle Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'Adelle@restaurant.com',
     'icon': 'adele.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Dublin Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'dublin@restaurant.com',
     'icon': 'dublin.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Castel Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'castel@restaurant.com',
     'icon': 'castel.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Mokup Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'mokup@restaurant.com',
     'icon': 'mokup.jpeg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Andrew Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'Andrew@restaurant.com',
     'icon': 'andrew.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Beluga Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'Beluga@restaurant.com',
     'icon': 'beluga.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Mirage Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'Andrew@restaurant.com',
     'icon': 'mirage.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Subway Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'Subway@restaurant.com',
     'icon': 'subway.jpg',
     },
    {'category': 'food-drink',
     'username': 'gabriel',
     'content': 'A quality and relaxing rural country pub, run by award winning owners, in the beautiful Berkshire village of Peasemore just a short drive from the A34 and junctions 13 and 14 of the M4. The building and decor are charming and rustic, with elegant modern touches.',
     'name': 'Pizza Hut Restaurant',
     'address': 'NY, Fifth Avenue, No.12, 219921',
     'phone': '+4932 9329 239 ',
     'email': 'pizza_hut@restaurant.com',
     'icon': 'pizza_hut.jpg',
     },
]



def add_data(apps, shema_editor):
    category = apps.get_model('listing', 'ListingCategory')
    listing = apps.get_model('listing', 'Listing')
    user = apps.get_model('auth', 'User')

    
    for item in LISTINGS:
        categ = category.objects.get(slug=item['category'])
        username = user.objects.get(username=item['username'])
        
        obj,created = listing.objects.get_or_create(category=categ,
                                                    user=username,
                                                    content=item['content'],
                                                    name=item['name'],
                                                    address=item['address'],
                                                    phone=item['phone'],
                                                    email=item['email'],
                                                    )
        icon_path = os.path.join(settings.BASE_DIR, 'static', 'images', item['icon'])
        with open(icon_path, 'rb') as icon_thumb:
            icon_instance = File(icon_thumb, os.path.basename(icon_path))
            obj.picture = icon_instance
            obj.save()


def remove_data(apps, schema_editor):
    listing = apps.get_model('listing', 'Listing')
    for item in LISTINGS:
        obj =listing.objects.get(name=item['name'])
        obj.delete()





class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_add_categ'),
    ]

    operations = [migrations.RunPython(add_data,remove_data)
    ]
