# Generated by Django 3.1.6 on 2021-04-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_add_listings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ['name']},
        ),
    ]
