# Generated by Django 3.1.6 on 2021-04-08 09:01
from __future__ import unicode_literals
from django.db import migrations
from django.core.files import File
import os
from django.conf import settings


POSTS= [
    {'user': 'gabriel',
     'picture': 'post_picture.jpg',
     'content': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
     'title': 'A trip to the Magic Land',},
    
    {'user': 'gabriel',
     'picture': 'post_picture2.jpg',
     'content': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
     'title': 'Best Places to visit in Andaman', },
    
    {'user': 'gabriel',
     'picture': 'post_picture3.jpg',
     'content': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
     'title': 'Canada extends travel restrictions into the 2021', },
    
    
    {'user': 'gabriel',
     'picture': 'post_picture3.jpg',
     'content': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
     'title': 'How social is revealing a new world for the travel industry', },
    
    {'user': 'gabriel',
     'picture': 'post_picture5.jpg',
     'content': 'Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.',
     'title': 'What Does a Travel Nurse Do?', },
]


def add_data(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    User = apps.get_model('auth', 'User')
    
    for post in POSTS:
        user = User.objects.get(username=post['user'])
        post_obj = Post.objects.create(user=user,
                        content=post['content'],
                        title=post['title'])
        picture_path = os.path.join(settings.BASE_DIR, 'static', 'images', post['picture'])
        with open(picture_path, 'rb') as picture:
            pic_object = File(picture, os.path.basename(picture_path))
            post_obj.picture = pic_object
            post_obj.save()


def remove_data(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    for post in POSTS:
        post_obj = Post.objects.get(title=post['title'])
        post_obj.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [ migrations.RunPython(add_data, remove_data)
    ]



    
    
